<template>
  <div class="card">

  </div>
</template>
<script></script>
<style scoped>
.card{
  width: 200px;
  height: 232px;
  border-radius: 5px;
  border: 1px solid #666;
  box-shadow: 0 5px 28px #666;
  margin-right: 20px;
  background-image: url("../assets/vue-js-egitim-background.jpg");
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
}
card:last-child{
  margin-right: 0;
}

</style>
